- regExp: [".*\\.md+$", "docs"]
  labels: ["documentation"]
- regExp: [ "go\\.mod", "go\\.sum" ]
  labels: ["dependencies"]
- regExp: ".*\\.github"
  labels: ["workflow"]
- regExp: ".*\\.go+$"
  labels: ["code"]
- regExp: ".*_test\\.go+$"
  labels: ["unittests"]
- regExp: "LICENSE"
  labels: ["LICENSE", "danger-zone"]

- regExp: "tggame"
  labels: ["game engine"]
- regExp: "main.go"
  labels: ["main.go", "danger-zone"]
